### ISSUE TITLE
00 -- Our Nice Game of Chess -- Carolina & Maddie

### ISSUE THREAD

**Issue by mfees** [mfees/TIY-Chessboard#1]
## Tasks
- [x] _Yak Shaving_ (XL)
  - [x] WIP Issue: `16 -- A Nice Game of Chess` with: (M)
    - [x] checkpoints, features, and estimates!
  - [x] Git Real (L)
  - [x] Research: (L)
    - [x] Printing table in js (M)
    - [x] making pieces move (L)
    - [x] linking elements in js (M)
- [x] _Chessboard_ (XL)
  - [x] Start by printing board with javascript (function) (L)
  - [x] Apply css styles (L)
    - [x] pieces (S)
    - [x] colors (S)
    - [x] hover states (S)
    - [x] make sure responsive is working correctly (M)
  - [ ] Making the pieces move (function) (L)
    - [x] make buttons in html (S)
    - [ ] link to javascript (M)

**Comment by mfees** [comment]
- [x] _WIP Branch:_ `TIY-Chessboard:master` (XL)
  - [x] a repository called `TIY-Chessboard`
    - [x] with everyone added as collaborators
  - [x] _multiple commits_ to `TIY-Chessboard:master` made by merging PRs _only_ (M)
  - [x] _multiple_ PRs in `TIY-Chessboard` (L)
    - [x] from `feature/` branches to `master`
    - [x] containing multiple commits
    - [x] reviewed by team members
  - [x] Starting with HTML5 Boilerplate, modify: (L)
    - [x] `css/main.css`
    - [x] `index.html`
    - [x] `js/main.js`
- [x] A fully-responsive chessboard with: (XL)
  - [ ] labels for ranks and files (L)
  - [x] pieces provided via unicode (S)
  - [x] hover states for each piece (not empty squares) (S)
- [x] A responsive interface that provides `<button>`'s for: (XL)
  - [x] playing the next move (L)
  - [x] resetting the board (M)
  - [x] playing _all remaining moves_ at once (L)
